type Project {
  name: String
  description: String
  repository: String
  technologies: [String]
  Website: String
}

type Dates {
  from: String
  to: String
}

type Job {
  position: String
  company: String
  location: String
  description: String
  dates: Dates
}

type FullProfile {
  image: String
  name: String
  description: String
  email: String
  technologies: [String]
  resume: String
  projects: [Project]
  jobs: [Job]
}

type Query {
  fullProfile(lang: String!): FullProfile!
}
