type Profile {
  Image: String
  Name: String
  Description: String
  Email: String
  Technologies: [String]
  Resume: String
}

type Project {
  Name: String
  Description: String
  Repository: String
  Technologies: [String]
  Website: String
}

type Dates {
  from: String
  to: String
}

type Job {
  position: String
  company: String
  location: String
  description: String
  dates: Dates
}

input Languaje {
  lang: String!
}

type Query {
  profile(input: Languaje!): Profile
  projects(input: Languaje!): [Project]
  jobs(input: Languaje!): [Job]
}
